import cv2
import socket
import pickle
import threading
import random
from numpy import arctan2, sqrt, pi
from cozmo_fsm import *
from pdb import set_trace

class PRINT(StateNode):
    def start(self,event=None):
        super().start(event)
        ghosts = dict(dict())
        self.post_completion()


class t(StateMachineProgram):
    def start(self):
        super().__init__(cam_viewer=False)
        super().start()

    def setup(self):
        """
            launch:  PRINT() =C=> launch
        """
        
        # Code generated by genfsm on Fri Oct 13 18:43:19 2017:
        
        launch = PRINT() .set_name("launch") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(launch) .add_destinations(launch)
        
        return self


